[package]
name = "cmd-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-version = "0.3.5"
regex = "1.5.5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
