name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.83.0


    - name: Build
      run: cargo build --release

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cmd-wrapper-linux-amd64
        path: target/release/cmd-wrapper

  release:
    name: On Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cmd-wrapper-linux-amd64
      - run: ls -R
      - run: mv cmd-wrapper cmd-wrapper-linux-amd64

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cmd-wrapper-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
